config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
devise_for :users

devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

  resources :answers do
    collection { put :create_average}
    collection { put :send_emails }
  end

  resources :members
  resources :avaliations do
    collection { put :send_email }

  end

end

app/models/answer.rb
class Answer < ApplicationRecord

  scope :by_avaliation_id, -> (avaliation_id) {
    where("avaliation_id = ?", avaliation_id)
  }

   def self.send_emails(members,avaliation)
    members.each do |member|
      SendAverageMailer.send_email_to_member(member,avaliation).deliver
    end
  end

  def self.create_average(answer_params)
    transaction do
      answer = Answer.new(answer_params)
      avaliation = Avaliation.where(finished: false).last
      answer.avaliation_id = avaliation.id
      answer.save
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  def send_emails
    members = Member.all
    avaliation = Avaliation.last_not_finished
    avaliation.generate_average(avaliation[0].id)
    sender = Answer.send_emails(members,avaliation)
    avaliation.finished(avaliation[0].id)


    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Pesquisa enviada com sucesso' }
      format.json { head :no_content }
    end
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.create_average(answer_params)

    respond_to do |format|
      if @answer != nil
        format.html { redirect_to answers_url, notice: 'Nota atribuida com sucesso'}
        format.json { redirect_to answers_url,status: created, location: @answer}
      else
        format.html { render :new}
        format.json {render json: answers_url,status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:average, :avaliation_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private
    def render_index
      render action: :index
    end
end

app/controllers/avaliations_controller.rb
class AvaliationsController < ApplicationController
  before_action :set_avaliation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /avaliations
  # GET /avaliations.json
  def index
    @avaliations = Avaliation.all
  end

  def send_email
    members = Member.all
    avaliation = Avaliation.last
    sender = Avaliation.send_emails(members,avaliation)
    respond_to do |format|
      format.html { redirect_to avaliations_url, notice: 'Pesquisa enviada com sucesso' }
      format.json { head :no_content }
    end
  end

  # GET /avaliations/1
  # GET /avaliations/1.json
  def show
  end

  # GET /avaliations/new
  def new
    @avaliation = Avaliation.new
  end

  # GET /avaliations/1/edit
  def edit
  end

  # POST /avaliations
  # POST /avaliations.json
  def create
    @avaliation = Avaliation.create_avaliation(avaliation_params,current_user)

    respond_to do |format|
      if @avaliation == nil
        format.html { render :new, notice: 'Somente pode ser criado avaliação quando terminada a anterior'}
      else
        format.html { redirect_to @avaliation, notice: 'Avaliation was successfully created.' }
        format.json { render :show, status: :created, location: @avaliation }
      end
    end
  end



  # PATCH/PUT /avaliations/1
  # PATCH/PUT /avaliations/1.json
  def update
    respond_to do |format|
      if @avaliation.update(avaliation_params)
        format.html { redirect_to @avaliation, notice: 'Avaliation was successfully updated.' }
        format.json { render :show, status: :ok, location: @avaliation }
      else
        format.html { render :edit }
        format.json { render json: @avaliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avaliations/1
  # DELETE /avaliations/1.json
  def destroy
    @avaliation.destroy
    respond_to do |format|
      format.html { redirect_to avaliations_url, notice: 'Avaliation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avaliation
      @avaliation = Avaliation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def avaliation_params
      params.require(:avaliation).permit(:user_id, :description, :validade)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avaliations_helper.rb
module AvaliationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/avaliations/_form.html.erb
<%= form_for(avaliation) do |f| %>
  <% if avaliation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(avaliation.errors.count, "error") %> prohibited this avaliation from being saved:</h2>

      <ul>
      <% avaliation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/avaliations/edit.html.erb
<h1>Editing Avaliation</h1>

<%= render 'form', avaliation: @avaliation %>

<%= link_to 'Show', @avaliation %> |
<%= link_to 'Back', avaliations_path %>

app/views/avaliations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pesquisas</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Description</th>
      <th>Finalizada</th>
      <th></th>
      <th>Média</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @avaliations.each do |avaliation| %>
        <tr>
        <td><%= avaliation.description %></td>
        <td><%= avaliation.finished %></td>
        <td><%= link_to 'Show', avaliation %></td>
        <td><%= avaliation.average %></td>
        <td><%= link_to 'Enviar pesquisa', send_email_avaliations_path(:id => avaliation.id),method: :put %></td>
        <td><%= link_to 'Finalizar pesquisa', send_emails_answers_path, method: :put if avaliation.finished == false %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Criar uma nova avaliação', new_avaliation_path %>

app/views/avaliations/new.html.erb
<h1>New Avaliation</h1>

<%= render 'form', avaliation: @avaliation %>

<%= link_to 'Back', avaliations_path %>

app/views/avaliations/send_average_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Olá <%= @member.name %></h1>
    <p>
      <h4> Esta é o resultado da sua pesquisa da pesquisaa de satisfação sobre: <%= @avaliation.description%></h4>
      
      <h4> Essa é a média final</h4>
      <h4><%= @avaliation.average%></h4>
      <li>     
</li>
    </p>
  </body>
</html>

app/views/avaliations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong
</p>

<p>
  <strong>Description:</strong>
  <%= @avaliation.description %>
</p>

<p>
  <strong>Validade:</strong>
  <%= @avaliation.validade %>
</p>

<%= link_to 'Edit', edit_avaliation_path(@avaliation) %> |
<%= link_to 'Back', avaliations_path %>